# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project_development
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: project_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: project_production
  username: postgres
  password: postgres

cucumber:
  <<: *test
